[build]
  command = "npm install --legacy-peer-deps && npm run build --legacy-peer-deps"
  publish = ".next"

[[redirects]]
  from = "/matscraft"
  to = "https://trello.com/b/e3XaYEti/matscraft"
  status = 301
